// app/layout.js (or your layout file if named differently)
import { Inter } from "next/font/google";
import Head from 'next/head';
import Footer from "../components/Footer";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Vinayan Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
    
      </Head>
      <body className={inter.className}>
      
      <Header/>
        {children}
       
        <Footer/>
      </body>
    
    </html>
  );
}
